// Wholesale essential-oil catalog for Dil Bahar Aromas.
// Prices are per kg (bulk). Source: client price list.

const perKg = (price, opts = {}) => ({
  size: '1 kg',
  price,
  stock: 25,
  isDefault: true,
  ...opts,
});

export const products = [
  {
    name: 'Cardamom Oil',
    localName: 'Elaichi Tel',
    slug: 'cardamom-oil',
    botanicalName: 'Elettaria cardamomum',
    emoji: '🫛',
    tagline: 'Sold per kg',
    shortDescription:
      'Bright, sweet-spicy cardamom (elaichi) oil for aromatherapy, perfumery and flavour. Wholesale pricing per kg.',
    description:
      '<p>Cardamom (elaichi) oil offers a sweet, warm-spicy aroma with a fresh top note. Distilled in Kannauj and supplied in bulk for perfumery, flavour and aromatherapy.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Aromatherapy', 'Perfumery', 'Flavour'],
    benefits: ['Uplifting sweet-spicy aroma', 'Pairs with citrus and woods', 'Bulk supply for manufacturers'],
    audience: 'Both',
    categorySlugs: ['essential-oils'],
    variants: [perKg(1800)],
    order: 1,
    ratingAvg: 4.8,
    ratingCount: 36,
    seo: {
      metaTitle: 'Cardamom (Elaichi) Oil — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Pure cardamom (elaichi) oil from Kannauj, supplied per kg. GC-MS verified for perfumery, flavour and aromatherapy.',
      keywords: ['cardamom oil', 'elaichi oil', 'cardamom oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Clove Oil (Loung Sp)',
    localName: 'Laung Tel',
    slug: 'clove-oil-laung',
    botanicalName: 'Syzygium aromaticum',
    emoji: '🌰',
    tagline: 'Sold per kg',
    shortDescription:
      'Potent, warming clove (laung) oil — special grade. Bulk supply for oral-care, hair and purifying blends.',
    description:
      '<p>Clove (laung) oil is rich in eugenol with a warm, spicy aroma. Special (Sp) grade, distilled in Kannauj and supplied per kg.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Hair', 'Oral care', 'Purifying'],
    benefits: ['Warm, spicy, eugenol-rich aroma', 'Traditional oral-care note', 'Bulk supply grade'],
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils'],
    variants: [perKg(900)],
    order: 2,
    ratingAvg: 4.7,
    ratingCount: 28,
    seo: {
      metaTitle: 'Clove (Laung) Oil Sp — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Special-grade clove (laung) oil from Kannauj, supplied per kg. Eugenol-rich, GC-MS verified.',
      keywords: ['clove oil', 'laung oil', 'clove oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Musk TPS',
    localName: 'Musk',
    slug: 'musk-tps',
    botanicalName: 'Synthetic musk compound (TPS)',
    emoji: '✨',
    tagline: 'Sold per kg · grade options',
    shortDescription:
      'Long-lasting musk TPS aroma compound for perfumery and attars. Available in TPS 1200 and TPS 2000 grades, priced per kg.',
    description:
      '<p>Musk TPS is a warm, sweet, long-lasting musk compound widely used as a base and fixative in perfumery and attar blends. Choose between the TPS 1200 and the richer TPS 2000 grade.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Compounded',
    useTags: ['Perfumery', 'Attar', 'Fixative'],
    benefits: ['Long-lasting musky base note', 'Excellent fixative for blends', 'Two grades for different budgets'],
    audience: 'Both',
    categorySlugs: ['luxury-oils', 'pooja-ritual-oils'],
    variants: [
      { size: 'TPS 1200', price: 1200, stock: 25, isDefault: true },
      { size: 'TPS 2000', price: 2000, stock: 20 },
    ],
    order: 3,
    ratingAvg: 4.6,
    ratingCount: 19,
    seo: {
      metaTitle: 'Musk TPS — Perfumery Compound, Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Musk TPS aroma compound in TPS 1200 and TPS 2000 grades. Long-lasting fixative for perfumery and attars, supplied per kg.',
      keywords: ['musk tps', 'musk compound', 'perfumery musk wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Eucalyptus Oil',
    localName: 'Eucalyptus',
    slug: 'eucalyptus-oil',
    botanicalName: 'Eucalyptus globulus',
    emoji: '🍃',
    images: ['/eucalyptus-oil.png'],
    tagline: 'Sold per kg',
    shortDescription:
      'Pure steam-distilled eucalyptus oil for respiratory support, cleaning and diffusing. Wholesale pricing per kg.',
    description:
      '<p>High-cineole eucalyptus oil suited to respiratory blends, natural cleaning sprays and diffusers. Distilled in Kannauj and supplied per kg.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Cold & congestion', 'Cleaning', 'Diffuser'],
    benefits: ['Clearing, camphoraceous aroma', 'High 1,8-cineole content', 'Bulk supply grade'],
    audience: 'Both',
    categorySlugs: ['essential-oils'],
    variants: [perKg(1200)],
    bestseller: true,
    order: 4,
    ratingAvg: 4.8,
    ratingCount: 64,
    seo: {
      metaTitle: 'Eucalyptus Oil — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Pure steam-distilled eucalyptus oil from Kannauj, supplied per kg. GC-MS verified, high-cineole.',
      keywords: ['eucalyptus oil', 'eucalyptus oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Ketaki Scent',
    localName: 'Kewda Floral',
    slug: 'ketaki-scent',
    botanicalName: 'Pandanus odorifer',
    emoji: '🏵️',
    tagline: 'Sold per kg',
    shortDescription:
      'Heritage kewda floral scent capturing the heady aroma of pandanus blossoms. Bulk supply per kg.',
    description:
      '<p>Ketaki (kewda) is a sweet, heady Indian floral note distilled from pandanus blossoms — a festive favourite in attars and pooja preparations. Supplied per kg.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Traditional distillation',
    useTags: ['Perfumery', 'Pooja'],
    benefits: ['Heady, sweet floral aroma', 'Traditional festive note', 'Beautiful in attar blends'],
    audience: 'Both',
    categorySlugs: ['pooja-ritual-oils', 'floral-waters'],
    variants: [perKg(1200)],
    order: 5,
    ratingAvg: 4.6,
    ratingCount: 21,
    seo: {
      metaTitle: 'Ketaki (Kewda Floral) Scent — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Heritage ketaki (kewda) floral scent from Kannauj, supplied per kg. A sweet, festive note for attars and pooja.',
      keywords: ['ketaki scent', 'kewda floral', 'ketaki attar wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Ambari Hina',
    localName: 'Hina Ambari',
    slug: 'ambari-hina',
    botanicalName: 'Traditional attar blend',
    emoji: '🌸',
    images: ['/ambari-hina.png'],
    tagline: 'Sold per kg',
    shortDescription:
      'Warm, complex ambari hina attar — a heritage North-Indian fragrance for perfumery and gifting. Bulk supply per kg.',
    description:
      '<p>Ambari hina is a traditional Kannauj attar built on a warm, spicy-amber accord. A celebratory fragrance and an excellent fixative base, supplied per kg.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Traditional deg-bhapka',
    useTags: ['Perfumery', 'Pooja', 'Gifting'],
    benefits: ['Rich, warm amber-floral attar', 'Excellent fixative base', 'Alcohol-free traditional attar'],
    audience: 'Both',
    categorySlugs: ['luxury-oils', 'pooja-ritual-oils'],
    variants: [perKg(750)],
    bestseller: true,
    order: 6,
    ratingAvg: 4.7,
    ratingCount: 17,
    seo: {
      metaTitle: 'Ambari Hina Attar — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Traditional ambari hina attar from Kannauj, supplied per kg. Warm amber-floral fragrance, alcohol-free base.',
      keywords: ['ambari hina', 'hina attar', 'ambari hina wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Kewra',
    localName: 'Kewda',
    slug: 'kewra',
    botanicalName: 'Pandanus odorifer',
    emoji: '💧',
    images: ['/kewra.png'],
    tagline: 'Sold per kg',
    shortDescription:
      'Authentic Kannauj kewra (kewda) for fragrance and flavour applications. Wholesale pricing per kg.',
    description:
      '<p>Kewra (kewda) carries the signature sweet aroma central to biryani, sweets and traditional perfumery. Distilled in Kannauj and supplied per kg.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Hydro-distillation',
    useTags: ['Perfumery', 'Flavour', 'Pooja'],
    benefits: ['Signature sweet kewda aroma', 'Versatile in flavour and perfumery', 'Bulk supply grade'],
    audience: 'Both',
    categorySlugs: ['floral-waters', 'essential-oils'],
    variants: [perKg(1200)],
    bestseller: true,
    order: 7,
    ratingAvg: 4.8,
    ratingCount: 49,
    seo: {
      metaTitle: 'Kewra (Kewda) — Wholesale per kg | Dil Bahar Aromas',
      metaDescription: 'Authentic Kannauj kewra (kewda) supplied per kg. Signature aroma for flavour, perfumery and pooja.',
      keywords: ['kewra', 'kewda', 'kewra wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Nilgiri Oil',
    localName: 'Neelgiri Tel',
    slug: 'nilgiri-oil',
    botanicalName: 'Eucalyptus globulus',
    emoji: '🌿',
    images: ['/nilgiri-oil.png'],
    tagline: 'Price on request',
    shortDescription:
      'Pure nilgiri (eucalyptus) oil with a sharp, cooling aroma. Contact us for current per-kg pricing.',
    description:
      '<p>Our nilgiri (eucalyptus) oil is steam-distilled at full strength with a bright, cooling aroma. Supplied in bulk — contact us for current per-kg pricing.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation (deg-bhapka)',
    useTags: ['Cold & congestion', 'Diffuser', 'Steam inhalation'],
    benefits: ['Fresh, cooling aroma', 'Traditional choice for congestion', 'Bulk supply grade'],
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    bestseller: true,
    order: 8,
    ratingAvg: 4.8,
    ratingCount: 31,
    seo: {
      metaTitle: 'Nilgiri (Eucalyptus) Oil — Bulk, Price on Request | Dil Bahar Aromas',
      metaDescription: 'Pure nilgiri (eucalyptus) oil from Kannauj, supplied in bulk. Contact us for current per-kg pricing.',
      keywords: ['nilgiri oil', 'neelgiri tel', 'nilgiri oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Mama Khaini',
    localName: 'Mama Khaini',
    slug: 'mama-khaini',
    botanicalName: 'Traditional aroma compound',
    emoji: '🍃',
    tagline: 'Price on request',
    shortDescription:
      'Mama Khaini aroma compound. Contact us for current per-kg pricing and specifications.',
    description:
      '<p>Mama Khaini is supplied in bulk for fragrance applications. Contact us for current per-kg pricing and specifications.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Compounded',
    useTags: ['Fragrance'],
    benefits: ['Distinctive aroma profile', 'Bulk supply grade'],
    audience: 'Both',
    categorySlugs: ['essential-oils'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    order: 9,
    ratingAvg: 4.5,
    ratingCount: 8,
    seo: {
      metaTitle: 'Mama Khaini — Bulk, Price on Request | Dil Bahar Aromas',
      metaDescription: 'Mama Khaini aroma compound supplied in bulk from Kannauj. Contact us for current per-kg pricing.',
      keywords: ['mama khaini'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Khus Oil',
    localName: 'Ruh Khus',
    slug: 'khus-oil',
    botanicalName: 'Vetiveria zizanioides',
    emoji: '🌾',
    images: ['/khus-oil.png'],
    tagline: 'Price on request',
    shortDescription:
      'Wild-vetiver khus oil with a deep, earthy, cooling aroma — Kannauj’s signature oil. Contact us for current per-kg pricing.',
    description:
      '<p>Khus (ruh khus) is distilled from wild vetiver roots and is one of Kannauj’s most celebrated oils, with a grounding, earthy-cool aroma treasured by perfumers. Supplied in bulk — contact us for current per-kg pricing.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation (deg-bhapka)',
    useTags: ['Perfumery', 'Hair & scalp', 'Cooling'],
    benefits: ['Grounding, long-lasting base note', 'Traditional hair-care oil', 'Naturally cooling aroma'],
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils', 'luxury-oils'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    bestseller: true,
    order: 10,
    ratingAvg: 4.9,
    ratingCount: 22,
    seo: {
      metaTitle: 'Khus (Ruh Khus / Vetiver) Oil — Bulk, Price on Request | Dil Bahar Aromas',
      metaDescription: 'Pure khus (wild vetiver / ruh khus) oil from Kannauj, supplied in bulk. Contact us for current per-kg pricing.',
      keywords: ['khus oil', 'ruh khus', 'vetiver oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Sandalwood Oil',
    localName: 'Chandan',
    slug: 'sandalwood-oil',
    botanicalName: 'Santalum album',
    emoji: '🪵',
    images: ['/sandalwood-oil.png'],
    tagline: 'Price on request',
    shortDescription:
      'Creamy, warm sandalwood (chandan) oil for skincare, meditation and pooja. Contact us for current per-kg pricing.',
    description:
      '<p>Sandalwood (chandan) carries a soft, creamy-woody aroma central to Indian skincare and ritual. Supplied in bulk — contact us for current per-kg pricing.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Skincare', 'Pooja', 'Meditation'],
    benefits: ['Soothing, warming aroma', 'Traditional skincare oil', 'Long-lasting perfumery note'],
    audience: 'Both',
    categorySlugs: ['skin-care-oils', 'pooja-ritual-oils', 'luxury-oils'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    bestseller: true,
    order: 11,
    ratingAvg: 4.9,
    ratingCount: 18,
    seo: {
      metaTitle: 'Sandalwood (Chandan) Oil — Bulk, Price on Request | Dil Bahar Aromas',
      metaDescription: 'Pure sandalwood (chandan) oil from Kannauj, supplied in bulk. Contact us for current per-kg pricing.',
      keywords: ['sandalwood oil', 'chandan oil', 'sandalwood oil wholesale'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Agarbatti Compound',
    localName: 'Agarbatti Compound',
    slug: 'agarbatti-compound',
    botanicalName: 'Fragrance compound',
    emoji: '🪔',
    images: ['/agarbatti-compound.png'],
    tagline: 'Price on request',
    shortDescription:
      'Ready-to-use fragrance compound for incense (agarbatti) manufacturing. Contact us for current per-kg pricing.',
    description:
      '<p>Our agarbatti compound is a blended fragrance base formulated for incense-stick manufacturing, delivering a consistent, long-lasting aroma. Supplied in bulk — contact us for current per-kg pricing.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Compounded',
    useTags: ['Incense', 'Manufacturing', 'Pooja'],
    benefits: ['Consistent, long-lasting fragrance', 'Formulated for agarbatti production', 'Bulk supply grade'],
    audience: 'B2B',
    categorySlugs: ['compounds', 'pooja-ritual-oils'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    order: 12,
    ratingAvg: 4.6,
    ratingCount: 11,
    seo: {
      metaTitle: 'Agarbatti Compound — Bulk Fragrance Base | Dil Bahar Aromas',
      metaDescription: 'Fragrance compound for agarbatti (incense) manufacturing, supplied in bulk from Kannauj. Contact us for per-kg pricing.',
      keywords: ['agarbatti compound', 'incense fragrance compound', 'agarbatti perfume'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Tobacco Compound (Gudaku)',
    localName: 'Gudaku',
    slug: 'tobacco-compound-gudaku',
    botanicalName: 'Fragrance compound',
    emoji: '🍂',
    images: ['/tobacco-compound-gudaku.png'],
    tagline: 'Price on request',
    shortDescription:
      'Aroma compound formulated for gudaku tobacco products. Contact us for current per-kg pricing.',
    description:
      '<p>Our gudaku tobacco compound is a fragrance base formulated for gudaku manufacturing. Supplied in bulk — contact us for current per-kg pricing and specifications.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Compounded',
    useTags: ['Manufacturing', 'Tobacco'],
    benefits: ['Consistent aroma for gudaku', 'Bulk supply grade'],
    audience: 'B2B',
    categorySlugs: ['compounds'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    order: 13,
    ratingAvg: 4.5,
    ratingCount: 6,
    seo: {
      metaTitle: 'Tobacco Compound (Gudaku) — Bulk | Dil Bahar Aromas',
      metaDescription: 'Gudaku tobacco fragrance compound supplied in bulk from Kannauj. Contact us for current per-kg pricing.',
      keywords: ['gudaku compound', 'tobacco compound gudaku'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Tobacco Compound (Gundi)',
    localName: 'Gundi',
    slug: 'tobacco-compound-gundi',
    botanicalName: 'Fragrance compound',
    emoji: '🍂',
    images: ['/tobacco-compound-gundi.png'],
    tagline: 'Price on request',
    shortDescription:
      'Aroma compound formulated for gundi tobacco products. Contact us for current per-kg pricing.',
    description:
      '<p>Our gundi tobacco compound is a fragrance base formulated for gundi manufacturing. Supplied in bulk — contact us for current per-kg pricing and specifications.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Compounded',
    useTags: ['Manufacturing', 'Tobacco'],
    benefits: ['Consistent aroma for gundi', 'Bulk supply grade'],
    audience: 'B2B',
    categorySlugs: ['compounds'],
    variants: [{ size: '1 kg', price: 0, stock: 0, isDefault: true }],
    order: 14,
    ratingAvg: 4.5,
    ratingCount: 5,
    seo: {
      metaTitle: 'Tobacco Compound (Gundi) — Bulk | Dil Bahar Aromas',
      metaDescription: 'Gundi tobacco fragrance compound supplied in bulk from Kannauj. Contact us for current per-kg pricing.',
      keywords: ['gundi compound', 'tobacco compound gundi'],
      structuredDataType: 'Product',
    },
  },
];
