// Product + batch seed data for Dil Bahar Aromas (Phase 2 catalog).
// Slugs intentionally match the frontend config so existing links resolve.

export const products = [
  {
    name: 'Eucalyptus / Nilgiri Oil',
    localName: 'Neelgiri Tel',
    slug: 'nilgiri-oil-neelgiri-tel',
    botanicalName: 'Eucalyptus globulus',
    emoji: '🌿',
    tagline: 'Cooling steam-inhalation classic',
    shortDescription:
      'Pure steam-distilled nilgiri (eucalyptus) oil with a sharp, cooling aroma — the traditional choice for cold, congestion and clear breathing.',
    description:
      '<p>Our Nilgiri (eucalyptus) oil is steam-distilled from fresh eucalyptus leaves and bottled at full strength. It carries the bright, camphoraceous note prized for steam inhalation during cold and congestion, and works beautifully in diffusers and DIY balms.</p><p>Like every Dil Bahar oil, each batch is GC-MS tested so you can verify the 1,8-cineole content with your batch code.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation (deg-bhapka)',
    useTags: ['Cold & congestion', 'Diffuser', 'Steam inhalation'],
    benefits: [
      'Eases blocked nose and seasonal congestion via steam inhalation',
      'Fresh, cooling aroma for diffusers and home sprays',
      'Blends well with peppermint and tea tree',
    ],
    howToUse:
      'Add 2–3 drops to a bowl of hot water for steam inhalation, or 4–5 drops in a diffuser. For topical use, dilute to 2% in a carrier oil.',
    ingredients: '100% pure Eucalyptus globulus leaf oil. No fillers, no carrier added.',
    safetyNotes:
      'For external/aromatic use. Keep away from children under 6 and avoid near the face of infants. Patch-test before topical use.',
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils'],
    variants: [
      { size: '15ml', sku: 'DBA-NIL-15', price: 199, mrp: 249, stock: 120, isDefault: true },
      { size: '50ml', sku: 'DBA-NIL-50', price: 549, mrp: 699, stock: 60 },
      { size: '100ml', sku: 'DBA-NIL-100', price: 999, mrp: 1249, stock: 40 },
    ],
    bestseller: true,
    order: 1,
    ratingAvg: 4.8,
    ratingCount: 214,
    relatedSlugs: ['ruh-khus-vetiver-oil', 'laung-clove-oil'],
    faqs: [
      { question: 'Is nilgiri oil the same as eucalyptus oil?', answer: 'Yes — nilgiri is the Hindi name for eucalyptus. Ours is Eucalyptus globulus, steam-distilled in Kannauj.' },
      { question: 'Can I apply it directly to skin?', answer: 'Always dilute to ~2% in a carrier oil before topical use. Never apply undiluted.' },
    ],
    seo: {
      metaTitle: 'Nilgiri (Eucalyptus) Oil — Pure, GC-MS Verified | Dil Bahar',
      metaDescription: 'Buy 100% pure nilgiri (eucalyptus) oil from Kannauj. Steam-distilled, GC-MS verified every batch. For cold, congestion & diffusers. COD available.',
      keywords: ['nilgiri oil', 'eucalyptus oil', 'neelgiri tel', 'eucalyptus oil for cold'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Ruh Khus (Vetiver) Oil',
    localName: 'Khus',
    slug: 'ruh-khus-vetiver-oil',
    botanicalName: 'Vetiveria zizanioides',
    emoji: '🌾',
    tagline: 'The oil of tranquility',
    shortDescription:
      'Wild-vetiver ruh khus with a deep, earthy, cooling aroma — Kannauj’s signature oil for perfumery, hair care and calm.',
    description:
      '<p>Ruh khus is distilled from wild vetiver roots and is one of Kannauj’s most celebrated oils. Its grounding, earthy-cool aroma deepens with time and is treasured by perfumers worldwide.</p><p>Traditionally used in hair-care rituals and as a natural coolant, every batch is fully traceable by GC-MS.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation (deg-bhapka)',
    useTags: ['Hair & scalp', 'Perfumery', 'Cooling'],
    benefits: [
      'Grounding, long-lasting base note for natural perfumery',
      'Traditionally used in scalp and hair-care oils',
      'Naturally cooling aroma for summer blends',
    ],
    howToUse: 'Use 1–2 drops in perfume blends, or dilute to 2% in a carrier oil for scalp massage.',
    ingredients: '100% pure wild vetiver (ruh khus) oil.',
    safetyNotes: 'For external use. Dilute before applying to skin. Patch-test recommended.',
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils', 'luxury-oils'],
    variants: [
      { size: '5ml', sku: 'DBA-RK-05', price: 899, mrp: 1099, stock: 80, isDefault: true },
      { size: '15ml', sku: 'DBA-RK-15', price: 2199, mrp: 2599, stock: 35 },
    ],
    bestseller: true,
    order: 2,
    ratingAvg: 4.9,
    ratingCount: 167,
    relatedSlugs: ['sandalwood-oil-chandan', 'hina-oil-heena'],
    faqs: [
      { question: 'Why is ruh khus more expensive?', answer: 'Wild vetiver yields very little oil per distillation and the roots take 18+ months to mature, making ruh khus a premium oil.' },
    ],
    seo: {
      metaTitle: 'Ruh Khus (Wild Vetiver) Oil from Kannauj | Dil Bahar Aromas',
      metaDescription: 'Pure ruh khus (wild vetiver) oil, steam-distilled in Kannauj and GC-MS verified. Earthy, cooling base note for perfumery and hair care.',
      keywords: ['ruh khus oil', 'vetiver oil', 'khus oil kannauj'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Sandalwood Oil',
    localName: 'Chandan',
    slug: 'sandalwood-oil-chandan',
    botanicalName: 'Santalum album',
    emoji: '🪵',
    tagline: 'Mysore-grade, skin & ritual',
    shortDescription:
      'Creamy, warm sandalwood (chandan) oil for radiant skin, meditation and pooja. Distilled and verified for purity.',
    description:
      '<p>Sandalwood (chandan) has been central to Indian skincare and ritual for centuries. Our oil carries the soft, creamy-woody aroma of true Santalum album, ideal for skincare blends, meditation and worship.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Skincare', 'Pooja', 'Meditation'],
    benefits: [
      'Soothing, warming aroma for meditation and pooja',
      'Traditionally used in skincare for an even, radiant tone',
      'Long-lasting heart-to-base perfumery note',
    ],
    howToUse: 'Dilute to 1–2% in a carrier oil for facial use, or diffuse 3–4 drops for meditation.',
    ingredients: '100% pure sandalwood oil.',
    safetyNotes: 'For external use. Dilute for skin. Patch-test before facial application.',
    audience: 'Both',
    categorySlugs: ['skin-care-oils', 'pooja-ritual-oils', 'luxury-oils'],
    variants: [
      { size: '5ml', sku: 'DBA-SAN-05', price: 1499, mrp: 1799, stock: 45, isDefault: true },
      { size: '10ml', sku: 'DBA-SAN-10', price: 2799, mrp: 3299, stock: 25 },
    ],
    bestseller: true,
    order: 3,
    ratingAvg: 4.9,
    ratingCount: 98,
    relatedSlugs: ['kesar-saffron-oil', 'hina-oil-heena'],
    faqs: [],
    seo: {
      metaTitle: 'Sandalwood (Chandan) Oil — Skin & Ritual | Dil Bahar Aromas',
      metaDescription: 'Pure sandalwood (chandan) oil for skincare, meditation and pooja. GC-MS verified, distilled in Kannauj.',
      keywords: ['sandalwood oil', 'chandan oil', 'chandan tel skincare'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Hina Oil',
    localName: 'Heena',
    slug: 'hina-oil-heena',
    botanicalName: 'Traditional attar blend',
    emoji: '🌸',
    tagline: 'Traditional wedding attar',
    shortDescription: 'A warm, complex heritage attar long associated with weddings and festive occasions in North India.',
    description:
      '<p>Hina is a traditional Kannauj attar built on a warm, spicy-floral accord. It is a celebratory fragrance worn at weddings and festivals, and a beautiful base for perfumery.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Traditional deg-bhapka',
    useTags: ['Perfumery', 'Pooja', 'Gifting'],
    benefits: ['Rich, warm attar for special occasions', 'Excellent fixative base for blends', 'Alcohol-free traditional attar'],
    howToUse: 'Apply a small dab to pulse points, or use 1–2 drops in attar blends.',
    ingredients: 'Traditional hina attar in a sandalwood base.',
    safetyNotes: 'For external use. Patch-test before use.',
    audience: 'Both',
    categorySlugs: ['pooja-ritual-oils', 'luxury-oils'],
    variants: [
      { size: '5ml', sku: 'DBA-HINA-05', price: 699, mrp: 849, stock: 50, isDefault: true },
      { size: '12ml', sku: 'DBA-HINA-12', price: 1499, mrp: 1799, stock: 30 },
    ],
    order: 4,
    ratingAvg: 4.7,
    ratingCount: 61,
    relatedSlugs: ['ketaki-scent-kewda-floral', 'sandalwood-oil-chandan'],
    faqs: [],
    seo: {
      metaTitle: 'Hina (Heena) Attar from Kannauj | Dil Bahar Aromas',
      metaDescription: 'Traditional hina attar from Kannauj — a warm, festive wedding fragrance. Alcohol-free, GC-MS verified base.',
      keywords: ['hina attar', 'heena oil', 'kannauj attar'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Kewra Water',
    localName: 'Kewda Jal',
    slug: 'kewra-water-kewda-jal',
    botanicalName: 'Pandanus odorifer',
    emoji: '💧',
    tagline: 'Food + cosmetic grade',
    shortDescription:
      'Authentic Kannauj kewra (kewda) water for biryani, sweets and skincare — available food-grade and cosmetic-grade.',
    description:
      '<p>Kewra water is the fragrant distillate of pandanus flowers, central to biryani, sweets and traditional skincare. Our food-grade kewra water adds a signature aroma to rice dishes and desserts, while the cosmetic grade works as a gentle facial toner.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Hydro-distillation',
    useTags: ['Biryani', 'Skincare', 'Sweets'],
    benefits: ['Signature aroma for biryani and Indian sweets', 'Gentle natural toner for skin', 'Alcohol-free floral water'],
    howToUse: 'Add 1 tsp to biryani or kheer near the end of cooking, or mist onto cleansed skin as a toner.',
    ingredients: 'Distilled kewra (pandanus) water.',
    safetyNotes: 'Food-grade variant is edible. Store cool and use within shelf life after opening.',
    audience: 'Both',
    categorySlugs: ['floral-waters', 'essential-oils'],
    variants: [
      { size: '100ml', sku: 'DBA-KEW-100', price: 199, mrp: 249, stock: 200, isDefault: true },
      { size: '250ml', sku: 'DBA-KEW-250', price: 399, mrp: 499, stock: 120 },
    ],
    order: 5,
    ratingAvg: 4.8,
    ratingCount: 143,
    relatedSlugs: ['ketaki-scent-kewda-floral'],
    faqs: [
      { question: 'Is the kewra water food-safe?', answer: 'Our food-grade kewra water is safe for culinary use. Choose the food-grade variant for cooking.' },
    ],
    seo: {
      metaTitle: 'Kewra Water (Kewda Jal) — Food & Cosmetic Grade | Dil Bahar',
      metaDescription: 'Authentic Kannauj kewra water for biryani, sweets and skincare. Food-grade and cosmetic-grade options. COD available.',
      keywords: ['kewra water', 'kewda jal', 'kewra water for biryani'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Laung (Clove) Oil',
    localName: 'Laung Tel',
    slug: 'laung-clove-oil',
    botanicalName: 'Syzygium aromaticum',
    emoji: '🌰',
    tagline: 'Warm, potent, purifying',
    shortDescription: 'Potent, warming clove (laung) oil traditionally used for oral care, hair and purifying blends.',
    description:
      '<p>Clove (laung) oil is rich in eugenol and carries a warm, spicy aroma. It has a long tradition in oral-care and hair preparations and is a powerful note in purifying blends.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Hair', 'Oral care', 'Purifying'],
    benefits: ['Warming, spicy aroma', 'Traditionally used in oral-care blends', 'Strong note for purifying diffuser blends'],
    howToUse: 'Highly potent — dilute to under 1% for any topical use. 1 drop in diffuser blends is plenty.',
    ingredients: '100% pure clove bud oil.',
    safetyNotes: 'Very strong; always heavily diluted. Avoid in pregnancy and on sensitive skin. Keep away from children.',
    audience: 'Both',
    categorySlugs: ['essential-oils', 'hair-growth-oils'],
    variants: [
      { size: '15ml', sku: 'DBA-LAU-15', price: 299, mrp: 379, stock: 90, isDefault: true },
      { size: '50ml', sku: 'DBA-LAU-50', price: 799, mrp: 999, stock: 40 },
    ],
    order: 6,
    ratingAvg: 4.7,
    ratingCount: 72,
    relatedSlugs: ['nilgiri-oil-neelgiri-tel'],
    faqs: [],
    seo: {
      metaTitle: 'Laung (Clove) Oil — Pure & GC-MS Verified | Dil Bahar Aromas',
      metaDescription: 'Pure clove (laung) oil from Kannauj. Warm, eugenol-rich and GC-MS verified. For hair, oral-care and purifying blends.',
      keywords: ['laung oil', 'clove oil', 'laung tel'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Kesar (Saffron) Oil',
    localName: 'Kesar Tel',
    slug: 'kesar-saffron-oil',
    botanicalName: 'Crocus sativus infusion',
    emoji: '🌺',
    tagline: 'Rare luxury distillation',
    shortDescription: 'A rare, precious saffron (kesar) oil for luxurious skincare and gifting.',
    description:
      '<p>Kesar (saffron) oil is among our rarest offerings — a luxurious infusion prized in skincare for its golden glow and delicate aroma. A perfect gift and a treat for the skin.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Infusion / distillation',
    useTags: ['Skincare', 'Gifting', 'Luxury'],
    benefits: ['Traditionally used for radiant, even-toned skin', 'Delicate luxurious aroma', 'Premium gifting option'],
    howToUse: 'Dilute to 1% in a carrier oil for facial use. A little goes a long way.',
    ingredients: 'Saffron-infused oil base.',
    safetyNotes: 'For external use. Patch-test before facial application.',
    audience: 'Both',
    categorySlugs: ['skin-care-oils', 'luxury-oils'],
    variants: [
      { size: '5ml', sku: 'DBA-KES-05', price: 1999, mrp: 2399, stock: 20, isDefault: true },
      { size: '10ml', sku: 'DBA-KES-10', price: 3699, mrp: 4299, stock: 12 },
    ],
    order: 7,
    ratingAvg: 4.9,
    ratingCount: 34,
    relatedSlugs: ['sandalwood-oil-chandan'],
    faqs: [],
    seo: {
      metaTitle: 'Kesar (Saffron) Oil — Luxury Skincare | Dil Bahar Aromas',
      metaDescription: 'Rare saffron (kesar) oil for radiant skin and gifting. A precious luxury distillation from Kannauj.',
      keywords: ['kesar oil', 'saffron oil', 'kesar tel for skin'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Cardamom Oil',
    localName: 'Elaichi',
    slug: 'cardamom-oil-elaichi',
    botanicalName: 'Elettaria cardamomum',
    emoji: '🫛',
    tagline: 'Sweet-spicy aromatic',
    shortDescription: 'Bright, sweet-spicy cardamom (elaichi) oil for aromatherapy, perfumery and flavour.',
    description:
      '<p>Cardamom (elaichi) oil offers a sweet, warm-spicy aroma with a fresh top note. It uplifts diffuser blends, rounds out perfumes and lends an aromatic lift to gourmet applications.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Aromatherapy', 'Flavour', 'Perfumery'],
    benefits: ['Uplifting sweet-spicy aroma', 'Versatile in perfume and food applications', 'Pairs with citrus and woods'],
    howToUse: 'Use 2–3 drops in a diffuser, or 1 drop in perfumery blends.',
    ingredients: '100% pure cardamom seed oil.',
    safetyNotes: 'For external/aromatic use unless food-grade. Dilute for skin.',
    audience: 'Both',
    categorySlugs: ['essential-oils'],
    variants: [
      { size: '5ml', sku: 'DBA-CAR-05', price: 499, mrp: 599, stock: 60, isDefault: true },
      { size: '15ml', sku: 'DBA-CAR-15', price: 1199, mrp: 1399, stock: 30 },
    ],
    order: 8,
    ratingAvg: 4.7,
    ratingCount: 41,
    relatedSlugs: ['laung-clove-oil'],
    faqs: [],
    seo: {
      metaTitle: 'Cardamom (Elaichi) Oil — Pure | Dil Bahar Aromas',
      metaDescription: 'Sweet-spicy cardamom (elaichi) oil from Kannauj. GC-MS verified for aromatherapy, perfumery and flavour.',
      keywords: ['cardamom oil', 'elaichi oil'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Ketaki Scent',
    localName: 'Kewda Floral',
    slug: 'ketaki-scent-kewda-floral',
    botanicalName: 'Pandanus odorifer',
    emoji: '🏵️',
    tagline: 'Heritage floral note',
    shortDescription: 'A heritage kewda floral scent capturing the heady aroma of pandanus blossoms.',
    description:
      '<p>Ketaki (kewda) is a beloved Indian floral note distilled from pandanus blossoms. Sweet, heady and unmistakably festive, it features in attars and pooja preparations.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Traditional distillation',
    useTags: ['Perfumery', 'Pooja'],
    benefits: ['Heady, sweet floral aroma', 'Traditional festive and ritual note', 'Beautiful in attar blends'],
    howToUse: 'Use 1–2 drops in attar and perfume blends, or as directed for ritual use.',
    ingredients: 'Ketaki (kewda) floral distillate.',
    safetyNotes: 'For external use. Patch-test before use.',
    audience: 'Both',
    categorySlugs: ['pooja-ritual-oils', 'floral-waters'],
    variants: [
      { size: '10ml', sku: 'DBA-KET-10', price: 599, mrp: 749, stock: 40, isDefault: true },
    ],
    order: 9,
    ratingAvg: 4.6,
    ratingCount: 23,
    relatedSlugs: ['kewra-water-kewda-jal', 'hina-oil-heena'],
    faqs: [],
    seo: {
      metaTitle: 'Ketaki (Kewda Floral) Scent | Dil Bahar Aromas',
      metaDescription: 'Heritage ketaki (kewda) floral scent from Kannauj — a sweet, festive note for attars and pooja.',
      keywords: ['ketaki scent', 'kewda floral', 'ketaki attar'],
      structuredDataType: 'Product',
    },
  },
  {
    name: 'Eucalyptus Essential Oil',
    localName: 'Eucalyptus',
    slug: 'eucalyptus-essential-oil',
    botanicalName: 'Eucalyptus globulus',
    emoji: '🍃',
    tagline: 'Pure steam-distilled',
    shortDescription: 'Pure steam-distilled eucalyptus essential oil for respiratory support, cleaning and diffusing.',
    description:
      '<p>Our eucalyptus essential oil is a clean, high-cineole distillation suited to respiratory blends, natural cleaning sprays and refreshing diffuser mixes.</p>',
    origin: 'Kannauj, India',
    extractionMethod: 'Steam distillation',
    useTags: ['Cold & congestion', 'Cleaning', 'Diffuser'],
    benefits: ['Clearing aroma for congestion', 'Fresh note for natural cleaning blends', 'High 1,8-cineole content'],
    howToUse: 'Diffuse 4–5 drops, or add to homemade cleaning sprays. Dilute to 2% for topical use.',
    ingredients: '100% pure Eucalyptus globulus oil.',
    safetyNotes: 'Keep away from young children. Dilute before topical use.',
    audience: 'Both',
    categorySlugs: ['essential-oils'],
    variants: [
      { size: '15ml', sku: 'DBA-EUC-15', price: 199, mrp: 249, stock: 100, isDefault: true },
      { size: '100ml', sku: 'DBA-EUC-100', price: 949, mrp: 1149, stock: 35 },
    ],
    order: 10,
    ratingAvg: 4.8,
    ratingCount: 88,
    relatedSlugs: ['nilgiri-oil-neelgiri-tel', 'laung-clove-oil'],
    faqs: [],
    seo: {
      metaTitle: 'Eucalyptus Essential Oil — Pure | Dil Bahar Aromas',
      metaDescription: 'Pure steam-distilled eucalyptus essential oil from Kannauj. GC-MS verified for respiratory, cleaning and diffuser use.',
      keywords: ['eucalyptus essential oil', 'eucalyptus oil india'],
      structuredDataType: 'Product',
    },
  },
];

export const batches = [
  {
    batchCode: 'DBA-2025-KH-04',
    productSlug: 'ruh-khus-vetiver-oil',
    productName: 'Ruh Khus (Vetiver) Oil',
    oilName: 'Wild Vetiver',
    distilledOn: new Date('2025-02-12'),
    testedOn: new Date('2025-02-20'),
    purity: '99.2%',
    method: 'GC-MS',
    labName: 'Independent NABL-accredited lab',
    gcmsReportUrl: 'https://example.com/coa/DBA-2025-KH-04.pdf',
    keyComponents: [
      { name: 'Khusimol', percentage: 12.4 },
      { name: 'Vetiverol', percentage: 9.1 },
      { name: 'Isovalencenol', percentage: 6.3 },
    ],
    notes: 'Distilled from 18-month wild vetiver roots.',
    isPublic: true,
  },
  {
    batchCode: 'DBA-2025-NIL-09',
    productSlug: 'nilgiri-oil-neelgiri-tel',
    productName: 'Eucalyptus / Nilgiri Oil',
    oilName: 'Eucalyptus globulus',
    distilledOn: new Date('2025-03-03'),
    testedOn: new Date('2025-03-08'),
    purity: '99.6%',
    method: 'GC-MS',
    labName: 'Independent NABL-accredited lab',
    gcmsReportUrl: 'https://example.com/coa/DBA-2025-NIL-09.pdf',
    keyComponents: [
      { name: '1,8-Cineole (Eucalyptol)', percentage: 82.5 },
      { name: 'α-Pinene', percentage: 7.2 },
      { name: 'Limonene', percentage: 4.1 },
    ],
    notes: 'High-cineole respiratory grade.',
    isPublic: true,
  },
  {
    batchCode: 'DBA-2025-SAN-02',
    productSlug: 'sandalwood-oil-chandan',
    productName: 'Sandalwood Oil',
    oilName: 'Santalum album',
    distilledOn: new Date('2025-01-18'),
    testedOn: new Date('2025-01-25'),
    purity: '98.9%',
    method: 'GC-MS',
    labName: 'Independent NABL-accredited lab',
    gcmsReportUrl: 'https://example.com/coa/DBA-2025-SAN-02.pdf',
    keyComponents: [
      { name: 'α-Santalol', percentage: 48.6 },
      { name: 'β-Santalol', percentage: 21.3 },
    ],
    notes: 'Creamy, high-santalol profile.',
    isPublic: true,
  },
];
